\version "2.24.2"

tempoE-II-VIa = \tempoMarkup "[no tempo]"
tempoE-II-VIb = \tempoMarkup "Largo"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl.ly"
\include "notes/vla.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
