\version "2.24.2"

tempoD-II-Va = \tempoMarkup "[Allegro]"
tempoD-II-Vb = \tempoMarkup "Adagio"
tempoD-II-Vc = \tempoMarkup "Allegro"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
