\version "2.24.2"

tempoG-VIIa = \tempoMarkup "Presto"
tempoG-VIIb = \tempoMarkup "Andante"
tempoG-VIIc = \tempoMarkup "Adagio"
tempoG-VIId = \tempoMarkup "Allabreve"
tempoG-VIIe = \tempoMarkup "Adagio"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
