\version "2.24.2"

tempoF-IV-IISalve = \tempoMarkup "Larghetto"
tempoF-IV-IIAdTe = \tempoMarkup "Andante"
tempoF-IV-IIAdTeB = \tempoMarkup "Adagio"
tempoF-IV-IIEia = \tempoMarkup "Vivace"
tempoF-IV-IIEtIesum = \tempoMarkup "Largo"
tempoF-IV-IIOClemens = \tempoMarkup "Andante"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
