\version "2.24.2"

tempoC-III-XXIVa = \tempoMarkup "Allegro moderato"
tempoC-III-XXIVb = \tempoTitleMarkup "Chorus" "Andante"
tempoC-III-XXIVc = \tempoMarkup "Allegretto"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
