\version "2.24.2"

tempoC-III-XXVa = \tempoTitle "Recitativo"
tempoC-III-XXVb = \tempoTitleMarkup "Aria" "Andante"
tempoC-III-XXVc = \tempoTitleMarkup "Chorus" "Adagio"
tempoC-III-XXVd = \tempoMarkup "Tempo moderato"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
