\version "2.24.2"

tempoD-IV-IVa = \tempoMarkup "Adagio"
tempoD-IV-IVb = \tempoMarkup "Allegro"
tempoD-IV-IVc = \tempoMarkup "[Allegro]"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
