\version "2.24.2"

tempoC-III-XXVIa = \tempoMarkup "Recitativo"
tempoC-III-XXVIb = \tempoTitleMarkup "Aria" "Andante"
tempoC-III-XXVIc = \tempoTitleMarkup "Chorus" "Adagio un poco"
tempoC-III-XXVId = \tempoMarkup "Andante"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
