\version "2.24.2"

tempoG-XVIIIa = \tempoMarkup "Presto"
tempoG-XVIIIb = \tempoMarkup "Andante"
tempoG-XVIIIc = \tempoMarkup "Adagio"
tempoG-XVIIId = \tempoMarkup "Allabreve"
tempoG-XVIIIe = \tempoMarkup "Adagio"

\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
