\version "2.24.2"

tempoC-II-IVa = \tempoMarkup "Allegro"
tempoC-II-IVb = \tempoMarkup "Adagio"
tempoC-II-IVc = \tempoMarkup "Larghetto"
tempoC-II-IVd = \tempoMarkup "Andante"
tempoC-II-IVe = \tempoMarkup "Allegro"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
