\version "2.24.2"

tempoD-II-IXDeProfundis = \tempoMarkup "Adagio"
tempoD-II-IXFiant = \tempoMarkup "Andante"
tempoD-II-IXSi = \tempoMarkup "Larghetto"
tempoD-II-IXQuia = \tempoMarkup "Adagio"
tempoD-II-IXEtIpse = \tempoMarkup "Allegro"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
