\version "2.24.2"

tempoA-XXIIKyrie = \tempoMarkup "Grave"
  tempoA-XXIIKyrieB = \tempoMarkup "Allegro"
tempoA-XXIIChriste = \tempoMarkup "Andante"
tempoA-XXIIKyrieFuga = \tempoMarkup "Adagio"
  tempoA-XXIIKyrieFugaB = \tempoMarkup "Allegro"

tempoA-XXIIGloria = \tempoMarkup "Allegro"
  tempoA-XXIILaudamus = \tempoMarkup "Andante"
  tempoA-XXIIAdoramus = \tempoMarkup \markup \concat { "[Adagio] " \smaller \smaller \critnote }
  tempoA-XXIIGlorificamus = \tempoMarkup "Allegro"
tempoA-XXIIGratias = \tempoMarkup "Tempo giusto"
tempoA-XXIIDomine = \tempoMarkup "[Tempo giusto]"
tempoA-XXIIQuiTollis = \tempoMarkup "Larghetto"
tempoA-XXIIQuiSedes = \tempoMarkup "[Larghetto]"
  tempoA-XXIIQuiSedesB = \tempoMarkup "Adagio"
tempoA-XXIIQuoniam = \tempoMarkup "Allegro"
tempoA-XXIICumSancto = \tempoMarkup "Allegro"

\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/tr1.ly"
\include "notes/tr2.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
