\version "2.24.2"

tempoE-IV-IISalve = \tempoMarkup "Larghetto"
tempoE-IV-IIAdTe = \tempoMarkup "Andante"
tempoE-IV-IIAdTeB = \tempoMarkup "Adagio"
tempoE-IV-IIEia = \tempoMarkup "Vivace"
tempoE-IV-IIEtIesum = \tempoMarkup "Largo"
tempoE-IV-IIOClemens = \tempoMarkup "Andante"

\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
