\version "2.24.2"

tempoD-II-VIIDixit = \tempoMarkup "[Allegro]"
tempoD-II-VIIIudicabit = \tempoMarkup "Adagio"
tempoD-II-VIIImplebit = \tempoMarkup "Allegro"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/clno1.ly"
\include "notes/clno2.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/timp.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/org.ly"
