\version "2.24.2"

tempoG-IXa = \tempoMarkup "Andante"
tempoG-IXb = \tempoMarkup "Andante"
tempoG-IXc = \tempoMarkup "Adagio"
tempoG-IXd = \tempoMarkup "Vivace"
tempoG-IXe = \tempoMarkup "Adagio"

\include "notes/cnto.ly"
\include "notes/fag.ly"
\include "notes/trb1.ly"
\include "notes/trb2.ly"
\include "notes/vl1.ly"
\include "notes/vl2.ly"
\include "notes/S.ly"
\include "notes/A.ly"
\include "notes/T.ly"
\include "notes/B.ly"
\include "notes/chords.ly"
\include "notes/org.ly"
